### ISSUE TITLE
raise source.error("invalid group reference %d" % group, len(escape) - 1) re.error: invalid group reference 1 at position 130

### ISSUE THREAD

**Issue by 1N3** [ShielderSec/webtech#14]
Webtech was working fine for me for a while, but now I'm getting the following error.

Any ideas?

```
 root@kali2019  /pentest/mobile/testing  pip3 install webtech                                                                                                            SIGINT(2) ↵  ⚡  1144  13:50:39 
Requirement already satisfied: webtech in /usr/local/lib/python3.7/dist-packages (1.2.7)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from webtech) (2.18.4)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->webtech) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->webtech) (2018.8.24)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/lib/python3/dist-packages (from requests->webtech) (2.6)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3/dist-packages (from requests->webtech) (3.0.4)
```

```
 root@kali2019  ~  webtech -u https://xerosecurity.com                                                                                                                             ✔  ⚡  1151  13:46:17 
Traceback (most recent call last):
  File "/usr/local/bin/webtech", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/webtech/__main__.py", line 54, in main
    wt.start()
  File "/usr/local/lib/python3.7/dist-packages/webtech/webtech.py", line 132, in start
    temp_output = self.start_from_url(url)
  File "/usr/local/lib/python3.7/dist-packages/webtech/webtech.py", line 172, in start_from_url
    return self.perform(target)
  File "/usr/local/lib/python3.7/dist-packages/webtech/webtech.py", line 222, in perform
    target.check_html(tech, html)
  File "/usr/local/lib/python3.7/dist-packages/webtech/target.py", line 221, in check_html
    matches = re.search(source, self.data['html'], re.IGNORECASE)
  File "/usr/lib/python3.7/re.py", line 183, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.7/sre_parse.py", line 924, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.7/sre_parse.py", line 420, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.7/sre_parse.py", line 501, in _parse
    code = _escape(source, this, state)
  File "/usr/lib/python3.7/sre_parse.py", line 399, in _escape
    raise source.error("invalid group reference %d" % group, len(escape) - 1)
re.error: invalid group reference 1 at position 130
```

**Comment by TheZ3ro** [comment]
Hi!

It seems that the problem is caused by this regex in Wappalyzer's `apps.json` -> https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json#L8723

I've pushed a commit that fixes that regex and adds version detection for html regexes that was supported by Wappalyzer since long time ago
https://github.com/ShielderSec/webtech/commit/8d15119f34ab1742437251c9683d18291ab26d5b

Now we will proceed pushing a new version (1.2.8) of WebTech on pypi so it can be updated with
`pip3 install -U webtech`

Thanks for the report!

**Comment by 1N3** [comment]
Awesome, thanks! It worked.
