### ISSUE TITLE
No such file or directory: '/usr/local/lib/python3.8/dist-packages/webtech/apps.json'

### ISSUE THREAD

**Issue by 1N3** [ShielderSec/webtech#18]
Just started getting this error on a fresh Kali 2020.3 image. Any ideas?

```
kali@kali:~$ pip3 install -U webtech
Requirement already up-to-date: webtech in /usr/local/lib/python3.8/dist-packages (1.2.8)
Requirement already satisfied, skipping upgrade: requests in /usr/local/lib/python3.8/dist-packages (from webtech) (2.20.0)
Requirement already satisfied, skipping upgrade: idna<2.8,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests->webtech) (2.7)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests->webtech) (1.24.3)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->webtech) (2020.4.5.1)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/lib/python3/dist-packages (from requests->webtech) (3.0.4)
```
```
kali@kali:~$ webtech -u https://xerosecurity.com
Wappalyzer Database file not present.
Updating database...
Unable to update database, check your internet connection and Github.com availability.
Traceback (most recent call last):
  File "/usr/local/bin/webtech", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/webtech/__main__.py", line 53, in main
    wt = WebTech(options)
  File "/usr/local/lib/python3.8/dist-packages/webtech/webtech.py", line 69, in __init__
    with open(database.WAPPALYZER_DATABASE_FILE) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/webtech/apps.json'
```

**Comment by 1N3** [comment]
Not sure what caused this, but I fixed it by uninstalling and re-installing the package.
