### ISSUE TITLE
Getting RemoteDisconnected while downloading the database (during DB update)

### ISSUE THREAD

**Issue by h4r5h1t** [ShielderSec/webtech#32]
Getting RemoteDisconnected error while updating the database.
`webtech --version`
 webtech 1.3.2

```bash
ubuntu@ubuntu:~$ webtech --udb

Force update of Database file
Downloading database: https://raw.githubusercontent.com/ShielderSec/webtech/master/webtech/webtech.json
Downloading database: https://raw.githubusercontent.com/AliasIO/wappalyzer/master/src/technologies/a.json
The Wappalyzer database seems offline. Report this issue to: https://github.com/ShielderSec/webtech/
Downloading database: https://raw.githubusercontent.com/AliasIO/wappalyzer/master/src/technologies/b.json
Traceback (most recent call last):
  File "/usr/bin/webtech", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.10/site-packages/webtech/__main__.py", line 53, in main
    wt = WebTech(options)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/webtech/webtech.py", line 68, in __init__
    database.update_database(force=update)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/webtech/database.py", line 79, in update_database
    download()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/webtech/database.py", line 55, in download
    download_database_file("{}{}.json".format(WAPPALYZER_DATABASE_URL_BASE,c), os.path.join(DATA_DIR,"temp.json"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/webtech/database.py", line 37, in download_database_file
    response = urlopen(url)
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

**Comment by smaury** [comment]
Closed in https://github.com/ShielderSec/webtech/pull/33
