### ISSUE TITLE
Failed with html file parse

### ISSUE THREAD

**Issue by secu77** [ShielderSec/webtech#9]
When I try to read an html file (obtained with wget) I get an error:

```
root@kali:~/test# webtech -u file:///root/test/data.html
Traceback (most recent call last):
  File "/usr/local/bin/webtech", line 11, in <module>
    load_entry_point('webtech==1.2.6', 'console_scripts', 'webtech')()
  File "/usr/local/lib/python3.7/dist-packages/webtech-1.2.6-py3.7.egg/webtech/__main__.py", line 54, in main
    wt.start()
  File "/usr/local/lib/python3.7/dist-packages/webtech-1.2.6-py3.7.egg/webtech/webtech.py", line 132, in start
    temp_output = self.start_from_url(url)
  File "/usr/local/lib/python3.7/dist-packages/webtech-1.2.6-py3.7.egg/webtech/webtech.py", line 168, in start_from_url
    target.parse_http_file(url)
  File "/usr/local/lib/python3.7/dist-packages/webtech-1.2.6-py3.7.egg/webtech/target.py", line 120, in parse_http_file
    return self.parse_http_request(data)
  File "/usr/local/lib/python3.7/dist-packages/webtech-1.2.6-py3.7.egg/webtech/target.py", line 182, in parse_http_request
    replay_url = "https://" + host + replay_uri
UnboundLocalError: local variable 'host' referenced before assignment
```
I'm using like the example in the readme file:

`$ webtech -u file://response.txt`

**Comment by TheZ3ro** [comment]
You need to supply a valid HTTP responde to webtech, this include the HTTP headers.
You can get them for example by running `curl -kis http://website > resp.txt` and then `webtech -u file://resp.txt`

I've pushed a new commit (available in the next version) that return a nice error message instead of an exception:
https://github.com/ShielderSec/webtech/commit/fdb0ed99f8d532626b4a80632795eafece358767
